# Generated by Django 2.0.7 on 2018-12-16 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='how_much',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instance',
            name='when',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
    ]
